version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=adam
      - POSTGRES_PASSWORD=adam123
    ports:
      - "5432:5432"
  web:
    build: . # this is already in file "Dockerfile", "." means that this is in the same location
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db

  postgis:
    image: cmihai/postgis
    container_name: postgis
    ports:
      - '5433:5433'
    environment:
      POSTGRES_PASSWORD: adam123
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: yossarian2k@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - postgis

volumes:
  pgdata: